# Digital Sky Survey Using Decision Tree

- The dataset is obtained from [Kaggle](https://www.kaggle.com/lucidlenn/sloan-digital-sky-survey).
- Both notebook file and dataset can be found at [GitHub](https://github.com/elakiricoder/Digital_Sky_Survey_Decision_Tree).

## 1 - Imports 

In [37]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## 2 - Read File 

In [38]:
df = pd.read_csv('Skyserver_SQL2_27_2018 6_51_39 PM.csv')

In [39]:
df.head()

objid          ra       dec         u         g         r         i  \
0  1.237650e+18  183.531326  0.089693  19.47406  17.04240  15.94699  15.50342   
1  1.237650e+18  183.598371  0.135285  18.66280  17.21449  16.67637  16.48922   
2  1.237650e+18  183.680207  0.126185  19.38298  18.19169  17.47428  17.08732   
3  1.237650e+18  183.870529  0.049911  17.76536  16.60272  16.16116  15.98233   
4  1.237650e+18  183.883288  0.102557  17.55025  16.26342  16.43869  16.55492   

          z  run  rerun  camcol  field     specobjid   class  redshift  plate  \
0  15.22531  752    301       4    267  3.722360e+18    STAR -0.000009   3306   
1  16.39150  752    301       4    267  3.638140e+17    STAR -0.000055    323   
2  16.80125  752    301       4    268  3.232740e+17  GALAXY  0.123111    287   
3  15.90438  752    301       4    269  3.722370e+18    STAR -0.000111   3306   
4  16.61326  752    301       4    269  3.722370e+18    STAR  0.000590   3306   

     mjd  fiberid  
0  54922      491  
1  51615      541  
2  52023      513  
3  54922      510  
4  54922      512

## 4 - Split the Data

In [40]:
X = df.drop('class', axis=1)
y = df['class']

In [41]:
from sklearn.model_selection import train_test_split

In [42]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30)

## 5 - Train the model

In [43]:
from sklearn.tree import DecisionTreeClassifier

In [44]:
dtree = DecisionTreeClassifier()

In [45]:
dtree.fit(X_train,y_train)

DecisionTreeClassifier()

In [46]:
pred = dtree.predict(X_test)

## 6 - Evaluate the Model 

In [47]:
from sklearn.metrics import classification_report,confusion_matrix

In [48]:
print(confusion_matrix(y_test,pred))

[[1456   17    1]
 [  26  217    0]
 [   6    0 1277]]


In [49]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

      GALAXY       0.98      0.99      0.98      1474
         QSO       0.93      0.89      0.91       243
        STAR       1.00      1.00      1.00      1283

    accuracy                           0.98      3000
   macro avg       0.97      0.96      0.96      3000
weighted avg       0.98      0.98      0.98      3000



## 9 - Test a sample

In [50]:
test_index = 0
y_test_np = np.array(y_test)

print(f'Actual --> {y_test_np[test_index]}  --  Prediction --> {pred[test_index]}')

Actual --> STAR  --  Prediction --> STAR


In [51]:
# #Check all the test data
# for i in range(len(y_test)):
#     test_index = i
#     y_test_np = np.array(y_test)
 
#     print(f'Actual --> {y_test_np[test_index]}  --  Prediction --> {pred[test_index]}')
#     if y_test_np[test_index] != pred[test_index]:
#         print('********** Above is a wrong prediction **********')